version: "3.8"
services:
  # this is service name
  postgresdb:
    # lightweight version of postgres
    image: postgres:alpine

    ### MOUNT FILES INTO CONTAINER
    volumes:
      - "./postgres_db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

    ### ENVIRONMENTAL VARIABLES
    # environmental variables that will be used when docker
    # is loading up the container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ### NETWORKING
    # this will expose it to the localhost on port 5432 
    # this let's us directly psql into it
    # note - when running docker-compose up, the --service-ports 
    # tag is required to make this work
    ports:
      - "127.0.0.1:5432:5432"
    # Internally exposes it to other docker compose services
    # not to the localhost machine
    # the api should connect to the pgdatabase through this port
    expose:
      - "5431"
