# Probs want to include some pagination

query {
	allArticleinfos {
    nodes {
      articleId
      webTitle
      publicationDate
      apiGivenCategory
      articleType
      articlecontentByContentId {
        content
      }
    }
  }
}