# Probs want to include some pagination

query {
	allArticles {
		nodes {
      id
      title
      publicationDate
      articleType
      topicofarticlesByArticleId {
        totalCount 
        nodes {
          topicByTopicId {
            id
            name
          }
        }
      }
      mediaoutletByMediaOutletId {
        id
        name
      }    
    }
  }
}