query AllOfAUsersConfigurations($userId: Int! = 2) {
	allUserconfigurations (filter: {
    usrId: {
      equalTo: $userId
    }
  }) {
    totalCount
    nodes {
      id
      configName
      topicconfigurationsByUsrConfigId {
        nodes {
          topicByTopicId{
            id
            name
          }
        }
      }
    }
  }
}