# Grabs the names of all configurations a User has saved
# Note: can extend to grab the exact configurations, but better to make 
#   another query call for that once the user selects it based of the configName 
#   they gave it

query AllOfAUsersConfigurations($userId: Int!) {
	allUserconfigurations (filter: {
    usrId: {
      equalTo: $userId
    }
  }) {
    totalCount
    nodes {
      id
      configName
    }
  }
}