
mutation {
  createUserconfiguration
    (
    input: {
      userconfiguration:{
        configName: String
        usrId: String
      }
    }
    ) {
    userconfiguration {
      id
      configName
      topicconfigurationsByUsrConfigId {
        edges {
          node {
            id
          }
        }
      }
    }
  }
}