mutation {
  createTopicconfiguration
    (
    input: {
      topicconfiguration:{
        usrConfigId: Int!
        topicId: Int!
        topicName: String!
      }
    }
    ) {
    topicconfiguration {
     id
     topicName
    }
  }
}
