query SearchForTopic ($keyword: String) {
  allTopics(
    # condition: { name : $keyword }){
    filter:{
      name : {
        includesInsensitive: $keyword
      }
    }) {
    nodes {
			id
      name
      topicofarticlesByTopicId{
        totalCount 
      }      
    }
  }
}