# Grabs the top 5 (by default) articles from a given topic
# TODO: currently, it just orders the articles according to their primary key value
#       - This will need to change as we want it by a measure of prevelance

query TopArticlesFromTopic($topicId: Int!, $numOfArticles: Int! = 5) {
  topicById(id: $topicId) {
    topicofarticlesByTopicId(first: $numOfArticles, orderBy: PRIMARY_KEY_ASC) {
      nodes {
        articleByArticleId {
          id
          title
          publicationDate
          author
          mediaoutletByMediaOutletId {
            name
          }
        }
      }
    }
  }
}
