
query TopicArticlesByDate($topicId: Int!, $from: Datetime, $to: Datetime) {
  topicById(id: $topicId) {

      id
      name
      topicofarticlesByTopicId(filter: { 
  	    articleByArticleId: {
					and: [
            { 
              publicationDate: {
                greaterThanOrEqualTo: $from,
                lessThan: $to,
                isNull: false
              }
            },
            
          ]
        }
      }) {
        totalCount 
      }
    }
  }

#   {
#   "data": {
#     "topicById": {
#       "id": 2,
#       "name": "US news",
#       "topicofarticlesByTopicId": {
#         "totalCount": 25
#       }
#     }
#   }
# }

