# query TopicArticlesByDate($topicId: Int!, $from: Datetime, $to: Datetime) {
#   topicById(id: $topicId) {

#       id
#       name
#       topicofarticlesByTopicId(filter: { 
#   	    articleByArticleId: {
# 					and: [
#             { 
#               publicationDate: {
#                 greaterThanOrEqualTo: $from,
#                 lessThanOrEqualTo: $to,
#                 isNull: false
#               }
#             },
            
#           ]
#         }
#       }) {
#         totalCount 
#       }
#     }
#   }

query TopicArticlesByDate($topicId: Int!, $date: Datetime) {
  topicById(id: $topicId) {
      id
      name
      topicofarticlesByTopicId(filter: { 
  	    articleByArticleId: {
					and: [
            { 
              publicationDate: {
                equalTo: $date,
                isNull: false
              }
            },
            
          ]
        }
      }) {
        totalCount 
      }
    }
  }
